<a href="https://colab.research.google.com/github/TejDS/NUMPY/blob/master/NUMPY_END_TO_END.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy:**


It's an acronym for Numerical Python.It is a python library used for working with arrays and also has functions for working in domain of Linear Algebra,    Fourier Transform and Matrices.



**Difference Between List and Numpy**



*   Speed : List is slow and Numpy is fast.

    1.   Numpy is a fixed type. In numpy a number is represented in the form of 
         int32 so it represents number in total memory space of 4 bytes.
    2.   Lists represent the number with :
                  
                  (i) Size (int32)
                  (ii) Reference Count(How many times the number is specifically pointed at) (int64)
                  (iii) Object Type (int64)
                  (iv) Object Value (int64)

  3.   Numpy utilises contiguous memory for storing elements. Whereas list stores elements in a scattered pattern (certainly not next to each other in the memory) 


    









**Applications Of Numpy:**



1.   Mathematics
2.   Matplotlib
3.   Backend of Pandas
4.   Digital Photography
5.   Machine Learning



In [0]:
# Importing Numpy Library

import numpy as np 

In [2]:
a = np.array([1,2,3],dtype='int8')

print(f'a: {a}')

a: [1 2 3]


In [3]:
# Get Dimension

print(f'Dimension of a : {a.ndim}')

Dimension of a : 1


In [4]:
# Type and Size 

print(f'Type: {a.dtype}  Size: {a.itemsize}')

Type: int8  Size: 1


In [5]:
# Get Shape

a.shape

(3,)

In [6]:
# Get Total Size
print(a.size * a.itemsize)

print(a.nbytes)

3
3


In [0]:
# Accessing Elements in a array


b = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])

In [8]:
b.shape

(2, 9)

In [9]:
print(f'b: {b}')

b: [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [10]:
# Accessing Element 17 from second row. 
print(f'Choice one : {b[1][-2]}')
print(f'Choice two : {b[1,-2]}')


Choice one : 17
Choice two : 17


In [11]:
# Access Specific Row 
print(f'Choice one : {b[1]}')
print(f'Choice two : {b[1,:]}')

Choice one : [10 11 12 13 14 15 16 17 18]
Choice two : [10 11 12 13 14 15 16 17 18]


In [12]:
# Access Specific Column

print(b[:,1])

[ 2 11]


In [13]:
# Accessing Elements in more fancy way [startindex:endindex:stepsize]

b[0,1:6:2]

array([2, 4, 6])

In [14]:
# Replacing Specific Elements (15 with 20)

b[1,5] = 20
print(f'Replaced Matrix : {b}')

Replaced Matrix : [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 20 16 17 18]]


In [15]:
# Replacing Elements in a column

b[:,2] = [15,20]
print(b)

[[ 1  2 15  4  5  6  7  8  9]
 [10 11 20 13 14 20 16 17 18]]


**3-D**

In [0]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
print(f'3D Matrix : {c}')

3D Matrix : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
c.shape

(2, 2, 2)

In [19]:
c.ndim

3

In [20]:
c.dtype

dtype('int64')

In [21]:
print(c.diagonal())

[[1 7]
 [2 8]]


In [22]:
print(b.diagonal())

[ 1 11]


In [23]:
c[0]

array([[1, 2],
       [3, 4]])

In [24]:
c[1]

array([[5, 6],
       [7, 8]])

In [25]:
c[0,0]

array([1, 2])

In [26]:
c[0,0][0]

1

In [0]:
c[0,0][0] = 20 

In [28]:
print(c)

[[[20  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]]


**Initializing Different Type of Arrays**

In [0]:
# All 0's Matrix

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.zeros((2,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [0]:
# All 1's Matrix

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
np.full((2,3),90)

array([[90, 90, 90],
       [90, 90, 90]])

In [38]:
# Creating an array of size b 
np.full_like(b,32)

array([[32, 32, 32, 32, 32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32, 32, 32, 32, 32]])

In [39]:
# Random Decimal Numbers Between 0 and 1

np.random.rand(4,2)

array([[7.53187755e-01, 8.99636944e-01],
       [4.64543054e-02, 5.29705459e-04],
       [3.69079105e-01, 2.41014933e-01],
       [5.70429913e-01, 8.42110924e-01]])

In [40]:
np.random.rand(4,2,3)

array([[[0.11015335, 0.17417025, 0.03201234],
        [0.33428911, 0.33116292, 0.31250173]],

       [[0.47617836, 0.47848402, 0.57319718],
        [0.21918297, 0.84179142, 0.18786125]],

       [[0.67545596, 0.0819424 , 0.05832477],
        [0.87728318, 0.27226076, 0.24328788]],

       [[0.33698707, 0.22946374, 0.37199657],
        [0.85023683, 0.84642698, 0.95722424]]])

In [41]:
# Random decimal Numbers in the  shape of other matrix

np.random.random_sample(b.shape)

array([[0.30144579, 0.62347731, 0.65167141, 0.56089057, 0.63996023,
        0.33510421, 0.42785368, 0.5427045 , 0.96795452],
       [0.67780604, 0.60559302, 0.13954856, 0.90158417, 0.05622602,
        0.73743742, 0.71641893, 0.99305012, 0.04570503]])

In [42]:
# Random Integer Values
np.random.randint(3,7,size=(3,3))

array([[4, 5, 6],
       [6, 3, 6],
       [5, 3, 3]])

In [43]:
# Identity Matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Repeat An Array


arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [45]:
# Testing the fundamentals

output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
output[1:4,1:4] = 0

In [49]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
output[2,2] = 9

In [51]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# Copying an array

a = np.array([1,2,3])
b=a
b[0] = 100
print(a)

[100   2   3]


In [53]:
a

array([100,   2,   3])

In [0]:
# So the above code doesnt work for copying as b is refering to a any change in b effects a 

In [55]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


**Math**

In [0]:
a = np.array([1,2,3,])

In [57]:
a+2

array([3, 4, 5])

In [58]:
a-2

array([-1,  0,  1])

In [59]:
a*2

array([2, 4, 6])

In [60]:
a**2

array([1, 4, 9])

In [61]:
a/2

array([0.5, 1. , 1.5])

In [62]:
a//2

array([0, 1, 1])

In [63]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [64]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

**Linear Algebra**

In [65]:
# Rule of Matrix Multiplication is : Number of  columns in matrix a  must be equal to number of rows in matrix b
a = np.ones((2,3))

print(a)


b = np.full((3,2),2)

print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [66]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [67]:
# Find the determinant

a = np.identity(3)
np.linalg.det(a)

1.0

In [69]:
np.linalg.eigh(a)

(array([1., 1., 1.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [70]:
np.linalg.eigvals(a)

array([1., 1., 1.])

In [101]:
# Dot Product
np.dot(a,b)

110

**Statistics**

In [0]:
stats = np.array([[1,2,3],[4,5,6]])

In [74]:
np.min(stats)

1

In [75]:
np.max(stats)

6

In [76]:
np.sum(stats)

21

In [77]:
np.cumsum(stats)

array([ 1,  3,  6, 10, 15, 21])

In [78]:
np.cumproduct(stats)

array([  1,   2,   6,  24, 120, 720])

In [79]:
np.cumprod(stats)

array([  1,   2,   6,  24, 120, 720])

In [0]:
# Reorganizing Arrays

In [82]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
a = np.array([2,3,4,5])
b = np.array([6,7,8,9])

np.vstack([a,b,a,b])

array([[2, 3, 4, 5],
       [6, 7, 8, 9],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [85]:
np.hstack([a,b,a,b])

array([2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# All Method
my_array = [[True, False], [False, False]]
a_bool = np.all(my_array)
print(a_bool)

False


In [100]:
# Any Method (Atleast One element must be true)
my_array = [[True, False], [False, False]]
a_bool = np.any(my_array)
print(a_bool)

True
